[env:esp32-screen-test]
platform = espressif32@7.1.2
board = esp32dev
framework = arduino
platform_packages =
  framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32/releases/download/2.0.17/esp32-2.0.17.zip
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
